networks:
  laravel_network:
    driver: bridge

volumes:
  inventory_db_data:
    driver: local

services:
  # MongoDB for inventory service
  inventory_db_server:
    image: mongo:latest
    container_name: inventory_db_server
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - inventory_db_data:/data/db
    networks:
      - laravel_network
    ports:
      - "27020:27017"

  # Inventory service - Laravel
  inventory_service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: inventory_service
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - APP_NAME="Inventory microservice"
      - APP_ENV=local
      - APP_KEY=base64:q1eDmtCjlKGYONOXZgS4bd6q5LTq3NDhYQiiOwxg5TY=
      - APP_DEBUG=true
      - MONGO_URI=mongodb://root:root@inventory_db_server:27017
      - JWT_SECRET=fVJQQyVo7v2H4nYHcFAdmAw13RIcVxbDsakbVC8o4PkOVGe7K02HQn2pffI2NLo0
    ports:
      - "8889:80"
    depends_on:
      - inventory_db_server
    networks:
      - laravel_network
